image:
  file: .gitpod.Dockerfile

tasks:
- name: "Build PS2 Development Toolchain"
  init: |
    sudo mkdir /usr/local/ps2dev
    sudo chmod 777 /usr/local/ps2dev
    cd $GITPOD_REPO_ROOT && ./build-all.sh
